spring:
  data:
    mongodb:
      host: notifications-db
      port: 27017
      database: notifications
      username: mongodb
      password: password
      authentication-database: admin
      auto-index-creation: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: notifications-service-swagger
      use-pkce-with-authorization-code-grant: true

keycloak:
  url: http://keycloak:8080
  realm: questions-and-answers-app