services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    restart: on-failure
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - qa-app-net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    command: [ 'start-dev', '--import-realm' ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/keycloak.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/keycloak.key.pem
    volumes:
      - ~/certs/private.pem:/opt/keycloak/keycloak.key.pem
      - ~/certs/cert.crt:/opt/keycloak/keycloak.crt.pem
      - ./config/keycloak/question-and-answer-app-realm.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8180:8080"
      - "8443:8443"
    depends_on:
      - keycloak-db
    networks:
      - qa-app-net

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      qa-app-net:

  config-server:
    container_name: config-server
    build:
      args:
        JAR_FILE: ./config-server/build/libs/*.jar
      dockerfile: Dockerfile
    image: qa-app-config-server
    environment:
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/app/config/{application}/{profile}
    volumes:
      - ./config/cloud:/app/config
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8888/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - qa-app-net
    restart: on-failure

  eureka-server:
    container_name: eureka-server
    build:
      args:
        JAR_FILE: ./eureka-server/build/libs/*.jar
      dockerfile: Dockerfile
    image: qa-app-eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: cloud
    networks:
      - qa-app-net
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8761/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
    restart: always

  questions-service:
    container_name: questions-service
    build:
      args:
        JAR_FILE: ./questions-service/build/libs/*.jar
      dockerfile: Dockerfile
    image: qa-app-questions-service
    environment:
      SPRING_PROFILES_ACTIVE: cloud
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      eureka-server:
        condition: service_healthy
      qa-app-db:
        condition: service_started
      rabbitmq:
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - qa-app-net
    restart: always

  qa-app-db:
    container_name: qa-app-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questions
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - qa-db-data:/var/lib/postgresql/data
    networks:
      - qa-app-net

  users-service:
    container_name: users-service
    build:
      args:
        JAR_FILE: ./users-service/build/libs/*.jar
      dockerfile: Dockerfile
    image: qa-app-users-service
    environment:
      SPRING_PROFILES_ACTIVE: cloud
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8081/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      keycloak:
        condition: service_started
    restart: always
    networks:
      - qa-app-net

  notifications-service:
    container_name: notifications-service
    build:
      args:
        JAR_FILE: ./notifications-service/build/libs/*.jar
      dockerfile: Dockerfile
    image: qa-app-notifications-service
    environment:
      SPRING_PROFILES_ACTIVE: cloud
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8083/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      eureka-server:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      notifications-db:
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - qa-app-net
    restart: always

  notifications-db:
    image: mongo:8.2-noble
    container_name: notifications-db
    environment:
      MONGO_INITDB_DATABASE: notifications
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - qa-app-net
    volumes:
      - notifications-db-data:/data/db

  api-gateway:
    container_name: api-gateway
    build:
      args:
        JAR_FILE: ./api-gateway/build/libs/*.jar
      dockerfile: Dockerfile
    image: qa-app-api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: cloud
    ports:
      - "8082:8082"
    depends_on:
      questions-service:
        condition: service_healthy
      users-service:
        condition: service_healthy
    restart: always
    networks:
      - qa-app-net

volumes:
  qa-db-data:
  notifications-db-data:
  keycloak-db-data:

networks:
  qa-app-net:
    name: qa-app-net