version: '3.9'

services:
  questions-db:
    container_name: questions-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questions
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - questions-db-data:/var/lib/postgresql/data

volumes:
  questions-db-data: