server:
  port: 8081

spring:
  application:
    name: users-service

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${DB_NAME:users}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${spring.datasource.name}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

  cloud:
    config:
      enabled: false


eureka:
  client:
    enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    oauth:
      client-id: users-service-swagger
      use-pkce-with-authorization-code-grant: true

keycloak:
  admin:
    client-id: admin-cli
    client-secret: ${KEYCLOAK_ADMIN_SECRET:**********}

  realm: ${KEYCLOAK_REALM:question-and-answer-app}
  url: ${KEYCLOAK_URL:http://localhost:8180}
