spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://users-db:5432/users?sslmode=disable

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    oauth:
      client-id: users-service-swagger
      use-pkce-with-authorization-code-grant: true


keycloak:
  admin:
    client-id: admin-cli
    client-secret: ${KEYCLOAK_ADMIN_SECRET:**********}

  realm: question-and-answer-app
  url: http://keycloak:8080