spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: questions_user
    password: password
    url: jdbc:postgresql://qa-app-db:5432/questions

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true


  liquibase:
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: questions-service-swagger
      use-pkce-with-authorization-code-grant: true

keycloak:
  url: http://keycloak:8080
  realm: question-and-answer-app
