server:
  port: ${PORT:8080}

spring:
  application:
    name: questions-service

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${DB_NAME:questions}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${spring.datasource.name}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: "/api-docs"