server:
  port: 8083

spring:
  application:
    name: notifications-service

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${DB_NAME:notifications}
    username: ${DB_USER:notifications_user}
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${spring.datasource.name}

  jdbc:
    template:
      fetch-size: 100

  liquibase:
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: notifications-service-swagger
      use-pkce-with-authorization-code-grant: true

app:
  notifications:
    cleanup:
      cron: "0 0 2 * * ?"
      retention-days: 1
      enabled: true

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8180}
  realm: ${KEYCLOAK_REALM:question-and-answer-app}