server:
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowCredentials: true
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Vary
      routes:
        - id: questions-service-api-route
          uri: lb://questions-service
          predicates:
            - Path=/api/questions/** , /api/answers/**

        - id: questions-service-openapi-route
          uri: lb://questions-service
          predicates:
            - Path=/questions/v3/api-docs
          filters:
            - StripPrefix=1

        - id: users-service-route
          uri: lb://users-service
          predicates:
            - Path=/api/users/**

        - id: users-service-openapi-route
          uri: lb://users-service
          predicates:
            - Path=/users/v3/api-docs
          filters:
            - StripPrefix=1


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 1

springdoc:
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics